@extends('admin.layouts.app')
@section('page_title','Order Masuk')
@section('page_description','Pantau pesanan customer, cek status, dan lanjutkan follow-up melalui WhatsApp.')
@section('content')
<form class="mb-5 rounded-[1.5rem] border border-slate-200 bg-white p-4 shadow-soft dark:border-slate-800 dark:bg-slate-900" method="GET">
    <div class="grid gap-3 md:grid-cols-[1fr_260px_auto]">
        <label class="relative block"><i class="ph ph-magnifying-glass absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"></i><input name="search" value="{{ request('search') }}" placeholder="Cari invoice, customer, atau nomor HP" class="h-12 w-full rounded-2xl border border-slate-200 bg-slate-50 pl-11 pr-4 text-sm font-semibold outline-none transition focus:border-slate-950 focus:bg-white dark:border-slate-700 dark:bg-slate-800"></label>
        <select name="status" class="h-12 rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm font-semibold outline-none transition focus:border-slate-950 focus:bg-white dark:border-slate-700 dark:bg-slate-800"><option value="">Semua status</option>@foreach($statuses as $status)<option value="{{ $status }}" @selected(request('status')===$status)>@switch($status)@case('waiting_whatsapp_confirmation')Menunggu WA@break @case('confirmed')Dikonfirmasi@break @case('processed')Diproses@break @case('completed')Selesai@break @case('cancelled')Dibatalkan@break @default{{ str_replace('_',' ',$status) }}@endswitch</option>@endforeach</select>
        <button class="h-12 rounded-2xl bg-slate-950 px-5 text-sm font-extrabold text-white shadow-sm dark:bg-white dark:text-slate-950">Terapkan Filter</button>
    </div>
</form>

<section class="rounded-[1.5rem] border border-slate-200 bg-white shadow-soft dark:border-slate-800 dark:bg-slate-900" data-admin-table>
    <div class="border-b border-slate-100 p-4 dark:border-slate-800"><div class="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 class="font-extrabold">Daftar Order</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Datatable order dengan pencarian cepat dan sorting.</p></div><label class="relative block w-full md:max-w-xs"><i class="ph ph-magnifying-glass absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"></i><input data-datatable-search placeholder="Cari di tabel..." class="h-11 w-full rounded-2xl border border-slate-200 bg-slate-50 pl-11 pr-4 text-sm font-semibold outline-none dark:border-slate-700 dark:bg-slate-800"></label></div></div>
    <div class="admin-scrollbar overflow-x-auto"><table class="w-full min-w-[980px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500 dark:bg-slate-800/50 dark:text-slate-400"><tr><th data-sortable class="px-5 py-4">Invoice <i class="sort-icon ph ph-caret-up-down ml-1"></i></th><th data-sortable>Customer <i class="sort-icon ph ph-caret-up-down ml-1"></i></th><th data-sortable>Item <i class="sort-icon ph ph-caret-up-down ml-1"></i></th><th data-sortable>Total <i class="sort-icon ph ph-caret-up-down ml-1"></i></th><th>Status</th><th data-sortable>Tanggal <i class="sort-icon ph ph-caret-up-down ml-1"></i></th><th class="pr-5 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">
@forelse($orders as $order)<tr class="transition hover:bg-slate-50 dark:hover:bg-slate-800/40"><td class="px-5 py-4 font-extrabold">{{ $order->invoice_number }}</td><td><b>{{ $order->customer_name }}</b><br><span class="text-xs text-slate-500">{{ $order->customer_phone ?: '-' }}</span></td><td>{{ $order->items_count }} item</td><td class="font-extrabold">Rp {{ number_format($order->total,0,',','.') }}</td><td>@php $statusLabel = ['waiting_whatsapp_confirmation'=>'Menunggu WA','confirmed'=>'Dikonfirmasi','processed'=>'Diproses','completed'=>'Selesai','cancelled'=>'Dibatalkan'][$order->status] ?? str_replace('_',' ',$order->status); $statusClass = ['waiting_whatsapp_confirmation'=>'bg-amber-50 text-amber-700 dark:bg-amber-400/10 dark:text-amber-300','confirmed'=>'bg-blue-50 text-blue-700 dark:bg-blue-400/10 dark:text-blue-300','processed'=>'bg-violet-50 text-violet-700 dark:bg-violet-400/10 dark:text-violet-300','completed'=>'bg-emerald-50 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300','cancelled'=>'bg-red-50 text-red-700 dark:bg-red-400/10 dark:text-red-300'][$order->status] ?? 'bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-400'; @endphp<span class="rounded-full px-3 py-1 text-xs font-extrabold {{ $statusClass }}">{{ $statusLabel }}</span></td><td class="text-slate-500 dark:text-slate-400">{{ $order->created_at->format('d M Y H:i') }}</td><td class="pr-5 text-right"><a href="{{ route('admin.orders.show',$order) }}" class="inline-flex items-center gap-1 rounded-xl bg-slate-950 px-3 py-2 text-xs font-extrabold text-white dark:bg-white dark:text-slate-950">Detail <i class="ph ph-arrow-right"></i></a></td></tr>@empty<tr data-empty-row><td colspan="7" class="px-5 py-10 text-center text-slate-500">Belum ada order.</td></tr>@endforelse
</tbody></table></div>
    <div class="flex flex-col gap-3 border-t border-slate-100 p-4 text-sm dark:border-slate-800 sm:flex-row sm:items-center sm:justify-between"><div class="text-slate-500 dark:text-slate-400"><span data-datatable-info></span></div><div class="flex items-center gap-2"><select data-datatable-length class="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold dark:border-slate-700 dark:bg-slate-900"><option value="5">5 baris</option><option value="10" selected>10 baris</option><option value="20">20 baris</option></select><button type="button" data-datatable-prev class="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold disabled:opacity-40 dark:border-slate-700">Prev</button><button type="button" data-datatable-next class="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold disabled:opacity-40 dark:border-slate-700">Next</button></div></div>
</section><div class="mt-4">{{ $orders->links() }}</div>
@endsection
