@extends('admin.layouts.app')
@section('page_title','Banner Slider')
@section('page_description','Kelola gambar slider halaman depan. Setiap slide bisa punya gambar desktop, gambar mobile, teks promosi, tombol, urutan, dan status.')
@section('page_action')<a href="{{ route('admin.banners.create') }}" class="inline-flex items-center justify-center gap-2 rounded-2xl bg-slate-950 px-5 py-3 text-sm font-extrabold text-white shadow-sm dark:bg-white dark:text-slate-950"><i class="ph ph-plus-circle"></i> Tambah Slide</a>@endsection
@section('content')
<section class="rounded-[1.5rem] border border-slate-200 bg-white shadow-soft dark:border-slate-800 dark:bg-slate-900" data-admin-table>
    <div class="border-b border-slate-100 p-4 dark:border-slate-800"><div class="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 class="font-extrabold">Daftar Slide Banner</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Preview gambar, teks promosi, status, urutan, dan aksi banner dalam satu tabel.</p></div><label class="relative block w-full md:max-w-xs"><i class="ph ph-magnifying-glass absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"></i><input data-datatable-search placeholder="Cari slide..." class="h-11 w-full rounded-2xl border border-slate-200 bg-slate-50 pl-11 pr-4 text-sm font-semibold outline-none dark:border-slate-700 dark:bg-slate-800"></label></div></div>
    <div class="admin-scrollbar overflow-x-auto"><table class="w-full min-w-[1040px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500 dark:bg-slate-800/50 dark:text-slate-400"><tr><th data-sortable class="px-5 py-4">Slide <i class="sort-icon ph ph-caret-up-down ml-1"></i></th><th>Gambar Slider</th><th>Tombol</th><th data-sortable>Urutan <i class="sort-icon ph ph-caret-up-down ml-1"></i></th><th>Status</th><th class="pr-5 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">
@forelse($banners as $banner)
@php
    $imagePath = $banner->image_path ?? null;
    $imageUrl = $imagePath ? (\Illuminate\Support\Str::startsWith($imagePath, ['http://', 'https://', '/']) ? $imagePath : \Illuminate\Support\Facades\Storage::url($imagePath)) : null;
    $mobileImagePath = $banner->mobile_image_path ?? null;
    $mobileImageUrl = $mobileImagePath ? (\Illuminate\Support\Str::startsWith($mobileImagePath, ['http://', 'https://', '/']) ? $mobileImagePath : \Illuminate\Support\Facades\Storage::url($mobileImagePath)) : null;
@endphp
<tr class="transition hover:bg-slate-50 dark:hover:bg-slate-800/40"><td class="px-5 py-4"><div class="max-w-[360px]"><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-500 dark:bg-slate-800 dark:text-slate-400">{{ $banner->label ?: 'Tanpa label' }}</span><h3 class="mt-2 line-clamp-1 font-extrabold text-slate-950 dark:text-white">{{ $banner->title }}</h3><p class="mt-1 line-clamp-1 text-xs text-slate-500 dark:text-slate-400">{{ $banner->subtitle ?: '-' }}</p></div></td><td><div class="flex items-center gap-3"><div class="h-16 w-36 overflow-hidden rounded-2xl border border-slate-200 bg-slate-100 shadow-sm dark:border-slate-700 dark:bg-slate-800">@if($imageUrl)<img src="{{ $imageUrl }}" alt="{{ $banner->title }}" class="h-full w-full object-cover">@else<div class="grid h-full w-full place-items-center text-slate-400"><i class="ph ph-image text-2xl"></i></div>@endif</div><div class="text-xs font-semibold text-slate-500 dark:text-slate-400">@if($imageUrl)<div class="text-emerald-600 dark:text-emerald-300">Desktop siap</div>@else<div class="text-amber-600 dark:text-amber-300">Desktop kosong</div>@endif @if($mobileImageUrl)<div class="mt-1 text-emerald-600 dark:text-emerald-300">Mobile siap</div>@else<div class="mt-1">Mobile pakai desktop</div>@endif</div></div></td><td><span class="font-bold">{{ $banner->button_text ?: 'Lihat Produk' }}</span><br><span class="text-xs text-slate-400">{{ $banner->button_url ?: '#produk' }}</span></td><td>{{ $banner->sort_order }}</td><td><span class="rounded-full px-3 py-1 text-xs font-extrabold {{ $banner->is_active ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300' : 'bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-400' }}">{{ $banner->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td class="pr-5 text-right"><div class="inline-flex items-center gap-2"><a class="inline-flex items-center gap-1 rounded-xl border border-slate-200 px-3 py-2 text-xs font-extrabold dark:border-slate-700" href="{{ route('admin.banners.edit',$banner) }}"><i class="ph ph-pencil-simple"></i> Edit</a><form class="inline" method="POST" action="{{ route('admin.banners.destroy',$banner) }}" onsubmit="return confirm('Hapus slide banner ini?')">@csrf @method('DELETE') <button class="inline-flex items-center gap-1 rounded-xl border border-red-200 px-3 py-2 text-xs font-extrabold text-red-600 dark:border-red-900/60"><i class="ph ph-trash"></i> Hapus</button></form></div></td></tr>@empty<tr data-empty-row><td colspan="6" class="px-5 py-10 text-center text-slate-500">Belum ada slide banner.</td></tr>@endforelse
</tbody></table></div>
    <div class="flex flex-col gap-3 border-t border-slate-100 p-4 text-sm dark:border-slate-800 sm:flex-row sm:items-center sm:justify-between"><div class="text-slate-500 dark:text-slate-400"><span data-datatable-info></span></div><div class="flex items-center gap-2"><select data-datatable-length class="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold dark:border-slate-700 dark:bg-slate-900"><option value="5">5 baris</option><option value="10" selected>10 baris</option><option value="20">20 baris</option></select><button type="button" data-datatable-prev class="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold disabled:opacity-40 dark:border-slate-700">Prev</button><button type="button" data-datatable-next class="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold disabled:opacity-40 dark:border-slate-700">Next</button></div></div>
</section><div class="mt-4">{{ $banners->links() }}</div>
@endsection
