@extends('admin.layouts.app')
@section('page_title', $voucher->exists ? 'Edit Voucher' : 'Tambah Voucher')
@section('page_description','Buat kode promo dengan istilah yang mudah dipahami admin: potongan rupiah, persentase, minimal belanja, dan masa berlaku.')
@section('content')
<form method="POST" action="{{ $voucher->exists ? route('admin.vouchers.update',$voucher) : route('admin.vouchers.store') }}" class="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-soft dark:border-slate-800 dark:bg-slate-900">@csrf @if($voucher->exists)@method('PUT')@endif
    <div class="mb-5 flex items-start gap-3 border-b border-slate-100 pb-4 dark:border-slate-800">
        <span class="grid h-11 w-11 place-items-center rounded-2xl bg-emerald-50 text-emerald-600 dark:bg-emerald-400/10 dark:text-emerald-300"><i class="ph ph-ticket text-2xl"></i></span>
        <div><h2 class="font-extrabold">Informasi Voucher</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Voucher akan tampil di halaman customer dan bisa dipakai saat checkout.</p></div>
    </div>
    <div class="grid gap-4 lg:grid-cols-2">
        <label class="block"><span class="mb-2 block text-sm font-extrabold">Kode Promo</span><input name="code" value="{{ old('code',$voucher->code) }}" placeholder="HEMAT10" class="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-semibold uppercase outline-none transition focus:border-slate-950 focus:bg-white dark:border-slate-700 dark:bg-slate-800" required><small class="mt-1 block text-xs text-slate-400">Gunakan huruf/angka singkat, contoh: HEMAT10.</small></label>
        <label class="block"><span class="mb-2 block text-sm font-extrabold">Kalimat Promo</span><input name="label" value="{{ old('label',$voucher->label) }}" placeholder="Potongan Rp10.000 untuk pembelian tertentu" class="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-semibold outline-none transition focus:border-slate-950 focus:bg-white dark:border-slate-700 dark:bg-slate-800" required></label>
        <label class="block"><span class="mb-2 block text-sm font-extrabold">Jenis Potongan</span><select name="type" class="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-semibold outline-none transition focus:border-slate-950 focus:bg-white dark:border-slate-700 dark:bg-slate-800"><option value="fixed" @selected(old('type',$voucher->type)==='fixed')>Potongan nominal (Rupiah)</option><option value="percent" @selected(old('type',$voucher->type)==='percent')>Potongan persentase (%)</option></select></label>
        <label class="block"><span class="mb-2 block text-sm font-extrabold">Besar Potongan</span><input name="value" type="number" value="{{ old('value',$voucher->value) }}" placeholder="10000 atau 10" class="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-semibold outline-none transition focus:border-slate-950 focus:bg-white dark:border-slate-700 dark:bg-slate-800" required><small class="mt-1 block text-xs text-slate-400">Kalau pilih rupiah: 10000. Kalau pilih persen: 10.</small></label>
        <label class="block"><span class="mb-2 block text-sm font-extrabold">Minimal Belanja</span><input name="minimum_order" type="number" value="{{ old('minimum_order',$voucher->minimum_order ?? 0) }}" placeholder="0" class="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-semibold outline-none transition focus:border-slate-950 focus:bg-white dark:border-slate-700 dark:bg-slate-800"><small class="mt-1 block text-xs text-slate-400">Isi 0 jika tidak ada minimal belanja.</small></label>
    </div>
    <div class="mt-5 grid gap-4 lg:grid-cols-2">
        <label class="block"><span class="mb-2 block text-sm font-extrabold">Mulai Berlaku <span class="font-semibold text-slate-400">opsional</span></span><input name="starts_at" type="datetime-local" value="{{ old('starts_at', optional($voucher->starts_at)->format('Y-m-d\TH:i')) }}" class="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-semibold outline-none transition focus:border-slate-950 focus:bg-white dark:border-slate-700 dark:bg-slate-800"></label>
        <label class="block"><span class="mb-2 block text-sm font-extrabold">Berakhir <span class="font-semibold text-slate-400">opsional</span></span><input name="ends_at" type="datetime-local" value="{{ old('ends_at', optional($voucher->ends_at)->format('Y-m-d\TH:i')) }}" class="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-semibold outline-none transition focus:border-slate-950 focus:bg-white dark:border-slate-700 dark:bg-slate-800"></label>
    </div>
    <label class="mt-5 flex cursor-pointer items-start gap-3 rounded-2xl border border-slate-200 p-4 dark:border-slate-800"><input type="checkbox" name="is_active" value="1" class="mt-1 h-4 w-4" @checked(old('is_active',$voucher->is_active ?? true))><span><b class="block text-sm">Voucher Aktif</b><small class="text-slate-500 dark:text-slate-400">Voucher bisa digunakan customer.</small></span></label>
    <div class="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:items-center sm:justify-end"><a href="{{ route('admin.vouchers.index') }}" class="inline-flex items-center justify-center rounded-2xl border border-slate-200 px-6 py-3 text-sm font-extrabold dark:border-slate-700">Batal</a><button class="inline-flex items-center justify-center gap-2 rounded-2xl bg-slate-950 px-6 py-3 text-sm font-extrabold text-white dark:bg-white dark:text-slate-950">Simpan Voucher <i class="ph ph-check-circle"></i></button></div>
</form>
@endsection
