@extends('admin.layouts.app')
@section('page_title','Voucher')
@section('page_description','Kelola promo yang bisa digunakan customer saat checkout.')
@section('page_action')<a href="{{ route('admin.vouchers.create') }}" class="inline-flex items-center justify-center gap-2 rounded-2xl bg-slate-950 px-5 py-3 text-sm font-extrabold text-white shadow-sm dark:bg-white dark:text-slate-950"><i class="ph ph-plus-circle"></i> Tambah Voucher</a>@endsection
@section('content')
<section class="rounded-[1.5rem] border border-slate-200 bg-white shadow-soft dark:border-slate-800 dark:bg-slate-900" data-admin-table>
    <div class="border-b border-slate-100 p-4 dark:border-slate-800"><div class="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 class="font-extrabold">Daftar Voucher</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Cari, urutkan, lalu edit promo dengan cepat.</p></div><label class="relative block w-full md:max-w-xs"><i class="ph ph-magnifying-glass absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"></i><input data-datatable-search placeholder="Cari voucher..." class="h-11 w-full rounded-2xl border border-slate-200 bg-slate-50 pl-11 pr-4 text-sm font-semibold outline-none dark:border-slate-700 dark:bg-slate-800"></label></div></div>
    <div class="admin-scrollbar overflow-x-auto"><table class="w-full min-w-[860px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500 dark:bg-slate-800/50 dark:text-slate-400"><tr><th data-sortable class="px-5 py-4">Kode <i class="sort-icon ph ph-caret-up-down ml-1"></i></th><th>Promo</th><th>Jenis</th><th data-sortable>Nilai <i class="sort-icon ph ph-caret-up-down ml-1"></i></th><th>Minimal</th><th>Status</th><th class="pr-5 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">
@forelse($vouchers as $voucher)<tr class="transition hover:bg-slate-50 dark:hover:bg-slate-800/40"><td class="px-5 py-4"><span class="rounded-xl bg-slate-950 px-3 py-2 text-xs font-extrabold tracking-wide text-white dark:bg-white dark:text-slate-950">{{ $voucher->code }}</span></td><td class="max-w-[280px]"><div class="truncate font-bold">{{ $voucher->label }}</div>@if($voucher->starts_at || $voucher->ends_at)<div class="mt-1 text-xs text-slate-400">{{ optional($voucher->starts_at)->format('d M Y') ?: 'Sekarang' }} - {{ optional($voucher->ends_at)->format('d M Y') ?: 'Tanpa batas' }}</div>@endif</td><td>{{ $voucher->type === 'percent' ? 'Persentase' : 'Rupiah' }}</td><td class="font-extrabold">{{ $voucher->type === 'percent' ? $voucher->value.'%' : 'Rp '.number_format($voucher->value,0,',','.') }}</td><td>Rp {{ number_format($voucher->minimum_order ?? 0,0,',','.') }}</td><td><span class="rounded-full px-3 py-1 text-xs font-extrabold {{ $voucher->is_active ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300' : 'bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-400' }}">{{ $voucher->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td class="pr-5 text-right"><div class="inline-flex items-center gap-2"><a class="inline-flex items-center gap-1 rounded-xl border border-slate-200 px-3 py-2 text-xs font-extrabold dark:border-slate-700" href="{{ route('admin.vouchers.edit',$voucher) }}"><i class="ph ph-pencil-simple"></i> Edit</a><form class="inline" method="POST" action="{{ route('admin.vouchers.destroy',$voucher) }}" onsubmit="return confirm('Hapus voucher ini?')">@csrf @method('DELETE') <button class="inline-flex items-center gap-1 rounded-xl border border-red-200 px-3 py-2 text-xs font-extrabold text-red-600 dark:border-red-900/60"><i class="ph ph-trash"></i> Hapus</button></form></div></td></tr>@empty<tr data-empty-row><td colspan="7" class="px-5 py-10 text-center text-slate-500">Belum ada voucher.</td></tr>@endforelse
</tbody></table></div>
    <div class="flex flex-col gap-3 border-t border-slate-100 p-4 text-sm dark:border-slate-800 sm:flex-row sm:items-center sm:justify-between"><div class="text-slate-500 dark:text-slate-400"><span data-datatable-info></span></div><div class="flex items-center gap-2"><select data-datatable-length class="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold dark:border-slate-700 dark:bg-slate-900"><option value="5">5 baris</option><option value="10" selected>10 baris</option><option value="20">20 baris</option></select><button type="button" data-datatable-prev class="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold disabled:opacity-40 dark:border-slate-700">Prev</button><button type="button" data-datatable-next class="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold disabled:opacity-40 dark:border-slate-700">Next</button></div></div>
</section><div class="mt-4">{{ $vouchers->links() }}</div>
@endsection
