@extends('admin.layouts.app')
@section('page_title','Kategori')
@section('page_description','Atur kelompok produk agar katalog customer lebih mudah dipahami.')
@section('page_action')<a href="{{ route('admin.categories.create') }}" class="inline-flex items-center justify-center gap-2 rounded-2xl bg-slate-950 px-5 py-3 text-sm font-extrabold text-white shadow-sm dark:bg-white dark:text-slate-950"><i class="ph ph-plus-circle"></i> Tambah Kategori</a>@endsection
@section('content')
<section class="rounded-[1.5rem] border border-slate-200 bg-white shadow-soft dark:border-slate-800 dark:bg-slate-900" data-admin-table>
    <div class="border-b border-slate-100 p-4 dark:border-slate-800"><div class="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 class="font-extrabold">Daftar Kategori</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Gunakan pencarian cepat untuk menemukan kategori.</p></div><label class="relative block w-full md:max-w-xs"><i class="ph ph-magnifying-glass absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"></i><input data-datatable-search placeholder="Cari kategori..." class="h-11 w-full rounded-2xl border border-slate-200 bg-slate-50 pl-11 pr-4 text-sm font-semibold outline-none dark:border-slate-700 dark:bg-slate-800"></label></div></div>
    <div class="admin-scrollbar overflow-x-auto"><table class="w-full min-w-[780px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500 dark:bg-slate-800/50 dark:text-slate-400"><tr><th data-sortable class="px-5 py-4">Kategori <i class="sort-icon ph ph-caret-up-down ml-1"></i></th><th>Icon</th><th data-sortable>Produk <i class="sort-icon ph ph-caret-up-down ml-1"></i></th><th data-sortable>Urutan <i class="sort-icon ph ph-caret-up-down ml-1"></i></th><th>Status</th><th class="pr-5 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">
@forelse($categories as $category)<tr class="transition hover:bg-slate-50 dark:hover:bg-slate-800/40"><td class="px-5 py-4 font-extrabold">{{ $category->name }}</td><td><span class="inline-flex items-center gap-2 rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600 dark:bg-slate-800 dark:text-slate-300"><i class="ph {{ $category->icon }} text-base"></i> Icon</span></td><td>{{ $category->products_count }}</td><td>{{ $category->sort_order }}</td><td><span class="rounded-full px-3 py-1 text-xs font-extrabold {{ $category->is_active ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300' : 'bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-400' }}">{{ $category->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td class="pr-5 text-right"><div class="inline-flex items-center gap-2"><a class="inline-flex items-center gap-1 rounded-xl border border-slate-200 px-3 py-2 text-xs font-extrabold dark:border-slate-700" href="{{ route('admin.categories.edit',$category) }}"><i class="ph ph-pencil-simple"></i> Edit</a><form class="inline" method="POST" action="{{ route('admin.categories.destroy',$category) }}" onsubmit="return confirm('Hapus kategori ini?')">@csrf @method('DELETE') <button class="inline-flex items-center gap-1 rounded-xl border border-red-200 px-3 py-2 text-xs font-extrabold text-red-600 dark:border-red-900/60"><i class="ph ph-trash"></i> Hapus</button></form></div></td></tr>@empty<tr data-empty-row><td colspan="6" class="px-5 py-10 text-center text-slate-500">Belum ada kategori.</td></tr>@endforelse
</tbody></table></div>
    <div class="flex flex-col gap-3 border-t border-slate-100 p-4 text-sm dark:border-slate-800 sm:flex-row sm:items-center sm:justify-between"><div class="text-slate-500 dark:text-slate-400"><span data-datatable-info></span></div><div class="flex items-center gap-2"><select data-datatable-length class="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold dark:border-slate-700 dark:bg-slate-900"><option value="5">5 baris</option><option value="10" selected>10 baris</option><option value="20">20 baris</option></select><button type="button" data-datatable-prev class="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold disabled:opacity-40 dark:border-slate-700">Prev</button><button type="button" data-datatable-next class="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold disabled:opacity-40 dark:border-slate-700">Next</button></div></div>
</section><div class="mt-4">{{ $categories->links() }}</div>
@endsection
